image: Visual Studio 2019

before_build: 
    - nuget restore HW1/ResizeArray/ResizeArray.sln

build: 
    project: HW1/ResizeArray/ResizeArray.sln

test_script:
    - dotnet test HW1/ResizeArray/ResizeArray.sln
