image: Visual Studio 2019

environment:
    matrix:
        - solution_name: HW2/CsharpTasks/CsharpTasks.sln

before_build:
    - nuget restore HW2/CsharpTasks/CsharpTasks.sln

build_script:
    - msbuild HW2/CsharpTasks/CsharpTasks.sln

test_script:
    - dotnet test HW2/CsharpTasks/CsharpTasks.sln
